---
- name: Start mysql
  become: yes
  command: service mysql restart
  tags: mysql

- name: Set mysql password
  mysql_user:
    name: root
    password: "{{ mysql_root_pass }}"
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  tags: mysql

- name: Create db
  mysql_db:
    state: present
    name: "{{ mysql_db_name }}"
    login_user: root
    login_password: "{{ mysql_root_pass }}"
  notify: Import sql schema
  tags: mysql

- meta: flush_handlers
  tags: mysql

