---
- name: Copy nginx config
  template: 
    src: default.j2
    dest: /etc/nginx/sites-available/default
  tags: nginx

- name: Start nginx
  become: yes
  command: service nginx restart
  tags: nginx
